server:
  port: 9092
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        namespace: 97ac27db-2799-49b1-b06e-5de258ef94f8
        server-addr: 127.0.0.1:9090
        
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719
      
MICROSERVICE-ORDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
